#应用名称
spring:
  application:
    name: springboot-graduationproject
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/supermarketsystemgraduationproject?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: a+cIiNhjgPpR70ih8bQaBNRnHT7sg2OXQLuTOXZFDFnBAVDUn5RYa/uIZT55vSdRPnERB5Ex6asEUgRr5FckoA==
      druid:
        initial-size: 1
        min-idle: 3
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 30000
        validation-query: select 'x'
        test-while-idle: true
        #建议配置为false。获取连接时执行validationQuery检测连接是否有效，这个配置会降低性能
        test-on-borrow: false
        #建议配置为false。获取连接时执行validationQuery检测连接是否有效，这个配置会降低性能
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        #配置监控统计拦截的filters，去掉后监控界面sql无法统计
        filters: config,stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: ruid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOF4Zf+JqJWySfvMmX36Wkd9YiwcuSiqFKiwTVuVz6JJkKx8R7t9UT0wByM26Tc++tN4Lihfh1dt8iRV+X0LU7kCAwEAAQ==
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        #采集数据库监控的数据
        web-stat-filter:
          url-pattern: /*
          enabled: true
          exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        #展示监控信息
        stat-view-servlet:
          url-pattern: /druid/*
          allow: 127.0.0.1
          reset-enable: false
          #是否开启，设置为true才能打开监控页面
          enabled: true
          #druid监控登录页面的用户名
          login-username: root
          #druid监控登录页面的密码
          login-password: root
#配置端口号
server:
  port: 8088

system:
  expireTime: 10800

#配置日志打印
logging:
  file:
    path: d:/logs/springboot/springlog
  config: classpath:config/logback-spring.xml
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:com/sicau/*/*/*/mapper/*Mapper.xml
  type-aliases-package: com.sicau.*.springbootgraduationproject
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ASSIGN_ID:"mybatisplus分配ID，Long，Integer，String", ASSIGN_UUID:"分配UUID，String";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      #filed-strategy在高版本被废弃(3.1.2以后)
      #filed-strategy: NOT_EMPTY
      insert-strategy: not_empty
      select-strategy: not_empty
      update-strategy: not_empty
      #刷新mapper 调试神器
      refresh-mapper: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false